[package]
name = "rasterizer"
version = "0.1.0"
edition = "2021"

[lib]
name = "rasterizer"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
tobj = "3.2.4"
stl_io = "0.7.0"